app:
  name: "weapi"
  version: 1 # 0=debug 1=release
  lang: "en"
  zoneoffset: 8 # timezone offset, east 8
  static: "static"
  cacheDir: "./cache/"
  mediaDir: "./media/"
httpserver:
  addr: ":8888"
log:
  dir: "./log/"
db:
  type: "sqlite"
  # dsn: "devel:i18n@tcp(127.0.0.1:3306)/weapi_db?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
  dsn: "./wepai.db"
  active: 32
  idle: 30
  idletimeout: 14400
  debug: true
redis:
  addr: "127.0.0.1:6379"
  password: "i18n!@#"
  db: 0
