package enum

// session field name
const SessionField = "weapi"

// Default Value: 1024
const ENV_CONFIG_CACHE_SIZE = "CONFIG_CACHE_SIZE"

// Default Value: 10s
const ENV_CONFIG_CACHE_EXPIRED = "CONFIG_CACHE_EXPIRED"

// DB
const ENV_DB_DRIVER = "DB_DRIVER"
const ENV_DB_ACTIVE = "DB_ACTIVE"
const ENV_DB_IDLE = "DB_IDLE"
const ENV_DB_TIMEOUT = "DB_TIMEOUT"
const ENV_DSN = "DSN"
const ENV_SESSION_SECRET = "SESSION_SECRET"

const ENV_LOG_FILE = "LOG_FILE"
const ENV_DEBUG = "DEBUG"
const ENV_STATIC_DIR = "STATIC_DIR"
const ENV_HTML_DIR = "HTML_DIR"
const ENV_LANG = "LANG"
const ENV_ZONE_OFFSET = "ZONE_OFFSET"

// User Password salt
const ENV_SALT = "PASSWORD_SALT"
const ENV_AUTH_PREFIX = "AUTH_PREFIX"
const ENV_STATIC_ROOT = "STATIC_ROOT"

const KEY_USER_ACTIVATED = "USER_ACTIVATED"
const KEY_AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
const KEY_RESET_PASSWD_EXPIRED = "RESET_PASSWD_EXPIRED"
const KEY_VERIFY_EMAIL_EXPIRED = "VERIFY_EMAIL_EXPIRED"

const KEY_SITE_NAME = "SITE_NAME"
const KEY_SITE_SLOGAN = "SITE_SLOGAN"
const KEY_SITE_ADMIN = "SITE_ADMIN"
const KEY_SITE_URL = "SITE_URL"
const KEY_SITE_KEYWORDS = "SITE_KEYWORDS"
const KEY_SITE_DESCRIPTION = "SITE_DESCRIPTION"
const KEY_SITE_GA = "SITE_GA"
const KEY_SITE_COPYRIGHT = "SITE_COPYRIGHT"
const KEY_SITE_LOGO_URL = "SITE_LOGO_URL"
const KEY_SITE_FAVICON_URL = "SITE_FAVICON_URL"
const KEY_SITE_TERMS_URL = "SITE_TERMS_URL"
const KEY_SITE_PRIVACY_URL = "SITE_PRIVACY_URL"
const KEY_SITE_SIGNIN_URL = "SITE_SIGNIN_URL"
const KEY_SITE_SIGNUP_URL = "SITE_SIGNUP_URL"
const KEY_SITE_LOGOUT_URL = "SITE_LOGOUT_URL"
const KEY_SITE_RESET_PASSWORD_URL = "SITE_RESET_PASSWORD_URL"
const KEY_SITE_LOGIN_NEXT = "SITE_LOGIN_NEXT"
const KEY_SITE_USER_ID_TYPE = "SITE_USER_ID_TYPE"
const KEY_ADMIN_DASHBOARD = "ADMIN_DASHBOARD"

const ENV_CMS_API_PREFIX = "CMS_API_PREFIX"
const KEY_CMS_GUEST_ACCESS_API = "CMS_GUEST_ACCESS_API"
const KEY_CMS_UPLOAD_DIR = "CMS_UPLOAD_DIR"
const KEY_CMS_EXTERNAL_UPLOADER = "CMS_EXTERNAL_UPLOADER"
const KEY_CMS_MEDIA_PREFIX = "CMS_MEDIA_PREFIX"
const KEY_CMS_MEDIA_HOST = "CMS_MEDIA_HOST"
const KEY_CMS_API_HOST = "CMS_API_HOST"
const KEY_CMS_RELATION_COUNT = "CMS_RELATION_COUNT"
const KEY_CMS_SUGGESTION_COUNT = "CMS_SUGGESTION_COUNT"

// Cors
const CORS_ALLOW_ALL = "*"
const CORS_ALLOW_CREDENTIALS = "true"
const CORS_ALLOW_HEADERS = "Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Authorization, accept, origin, Cache-Control, X-Requested-With, X-Auth-Token"
const CORS_ALLOW_METHODS = "POST, OPTIONS, GET, PUT, PATCH, DELETE"
